// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQ4sciYtjbaTDw7Bimi7mMdJ9NWVBUcg',
    appId: '1:1041793241404:web:386596e34b90ec61070e39',
    messagingSenderId: '1041793241404',
    projectId: 'examen2-8afba',
    authDomain: 'examen2-8afba.firebaseapp.com',
    storageBucket: 'examen2-8afba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACwkMVdtnpjzESq5paVw2WSdvByowDSBg',
    appId: '1:1041793241404:android:ddcfd455eb0b6143070e39',
    messagingSenderId: '1041793241404',
    projectId: 'examen2-8afba',
    storageBucket: 'examen2-8afba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAr3gUFXio9iFsdZG499TqxTHjLpHwimE',
    appId: '1:1041793241404:ios:26b82d6d478a8cac070e39',
    messagingSenderId: '1041793241404',
    projectId: 'examen2-8afba',
    storageBucket: 'examen2-8afba.appspot.com',
    iosBundleId: 'com.example.examen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAr3gUFXio9iFsdZG499TqxTHjLpHwimE',
    appId: '1:1041793241404:ios:26b82d6d478a8cac070e39',
    messagingSenderId: '1041793241404',
    projectId: 'examen2-8afba',
    storageBucket: 'examen2-8afba.appspot.com',
    iosBundleId: 'com.example.examen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQ4sciYtjbaTDw7Bimi7mMdJ9NWVBUcg',
    appId: '1:1041793241404:web:b596d2574a4602e9070e39',
    messagingSenderId: '1041793241404',
    projectId: 'examen2-8afba',
    authDomain: 'examen2-8afba.firebaseapp.com',
    storageBucket: 'examen2-8afba.appspot.com',
  );
}
